name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main # Or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get next version
        id: get_version
        run: |
          # Default version
          VERSION="1.0"

          # Try to get the latest version tag
          latest_tag=$(git describe --abbrev=0 --tags 2>/dev/null)
          if [[ $? -eq 0 ]]; then
            # Extract the numeric part of the tag (e.g., "1.0" from "v1.0")
            version_number=$(echo "$latest_tag" | sed 's/^v//g')

            # Split the version into major and minor
            IFS='.' read -r MAJOR MINOR <<< "$version_number"

            # Increment the minor version
            MINOR=$((MINOR + 1))

            # If minor version is greater than 9, increment major and reset minor
            if [[ $MINOR -gt 9 ]]; then
              MAJOR=$((MAJOR + 1))
              MINOR=0
            fi
            VERSION="$MAJOR.$MINOR"
          else
            echo "No previous version tag found. Starting at 1.0"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "NEXT_VERSION=v$VERSION" >> $GITHUB_OUTPUT # for use in tags
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}:latest
